# -*- coding: utf-8 -*-
"""COMPRO 2-Frista Nabila Salsabila

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_hAHyNamjGn5OHaJmFEg5nljgoXviiNz

**String**
"""

nama = 'Frista Nabila Salsabia'
asal = "indonesia"

print(nama)

print(nama)

print(asal)

"""**Manipulasi String**"""

print(nama + asal)

print("halo, nama saya",nama)

print("Halo, nama saya", nama, "dan saya berasal dari", asal)

data_lengkap = nama + asal

print(data_lengkap)

"""**String + Non String**"""

asal_kota = "Bandar Lampung"
kode_pos = 35144  # Seharusnya ditetapkan sebagai variabel

asal_kota_kode_pos = asal_kota + str(kode_pos) # Perbaiki nama variabel di sini

print(asal_kota_kode_pos)

asal_kota_x3 = asal_kota * 3

print(asal_kota_x3)