# -*- coding: utf-8 -*-
"""Computer Programming-2, Casting

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B3SDUNLdXTPgKorjZQ-7vOelLKPXkQtR

**Tipe Data Casting**
"""

nama = 'Ujang'
usia = 20
lajang = True

print(type(nama))
print(type(usia))
print(type(lajang))

"""**Konversi Tipe Data**"""

usia = input('Masukkan usia anda:')

print(type(usia))

panjang = int(input('masukkan panjang:'))
lebar = int(input('Masukkan lebar'))

print(panjang * lebar)

a = 10/2

kata = 'Jeruk'*5

print(kata)

panjang = input('Masukkan panjang:')
lebar = input('Masukkan lebar:')
(contoh error)
print('luas=', panjang * lebar)

"""**Konversi String ke Numerik**"""

panjang = int(input('Masukkan panjang:'))
lebar = float(input('Masukkan lebar:'))

print('luas=', panjang * lebar)

nama = 'Wudi'
tahun_lahir = 2000

print(nama + ' lahir di tahun ' + str(tahun_lahir))