# -*- coding: utf-8 -*-
"""Compro 2-10/03/26- Frista Nabila S

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LjsJs9XXce4m-sfCdfyl32zM23Wtnwby

**Format specifiers**
"""

template = 'Halo, saya %s dari %s'

print(template % ('Lendis Fabri', 'Indonesia'))

"""**Fungsi Format ()**"""

template = 'Halo, saya {nama} dari {asal}'
template_2 = 'Saya suka makan {} dan minum {}'

print(template.format(nama='Lendis Fabri', asal='Indonesia'))
print(template_2.format('nasi goreng', 'air putih'))

"""**String Interpolation/F-**"""

nama = 'Lendis Fabri'
asal = 'Indonesia'

print(f'Perkenalkan saya {nama} dari {asal}˙𐃷˙')

"""**Memecah String Menjadi List dan Sebaliknya**"""

alamat = 'Surabaya, Jawa Timur, Indonesia'

print(alamat.split())

print(alamat.split(','))

print(alamat.split(', '))

"""**Memecah String Menjadi List dan Sebaliknya**"""

print('💗'.join(['aku', 'suka','python']))

print('🦖'.join(alamat.split(', ')))

"""**Mengubah String Menjadi Upper Case**"""

print('Halo selamat pagi!'.upper())

print('Halo Selamat Siang!'.upper())

"""**Mengubah String Menjadi Lower Case**"""

print('APA KABAR?'. lower())

print('Lagi Dimana?'. lower())

"""**Mengubah String Menjadi Title Case**"""

print('daun tidak pernah membenci angin'.title())

print('LASKAR PELANGI'.title())

"""**Mengubah String Menjadi Reverse Case**"""

print('Indonesia Adalah Negara Kepulauan'.swapcase())

print('aKu cInTa NeGeRiKu'.swapcase())

"""**Mencari Kata Pada String**"""

angka = '12345'

print('Index angka 3:', angka.find('3'))
print('Index angka 45:', angka.find('45'))
print('Index angka 35:', angka.find('35'))

asal = 'lampung'

print(asal.find('m'))

asal = 'lampung'

print(asal.find('pung'))

"""**Mereplace kata tertentu pada String**"""

ibu_kota = 'Jakarta'

print(ibu_kota.replace('a','i'))

print(ibu_kota.replace('kar','🦖'))

print(ibu_kota.replace('a',''))

"""**Menghitung Jumlah karakter yang muncul**"""

paragraf = 'Baru-baru ini telah ditemukan sebuah meteor di suatu sungai'
x = paragraf.count('di')

print(f'Kata "di" muncul sebanyal {x} kali')

paragraf = 'Baru-baru ini telah ditemukan sebuah meteor di suatu sungai'

print(paragraf.count('a'))