# -*- coding: utf-8 -*-
"""Escape character.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mcVPBq862WaezwDThl_Zo003AssYHI2K
"""

print('Dia Berkata: "Pergilah!"')

print("Aku menimpali: \"Apakah kau ingin aku 'angkat kaki'?!\"")

print("\\(^_^)/ (\\-_-/)")