# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JB5ZOf_SumHIYubUhH2zMTf4T79yHj6H

**Operasi In pada String**
"""

berita = '''Ramai-ramai developer di seluruh dunia mulai menggunakan
teks editor masa kini seperti Visual Studio Code,
atom, sublime text, dan text sebagainya.'''

print('sublime text' in berita)
print('notepad++' in berita)

"""**Memotong String**"""

nama = 'Lendis Fabri'
print(nama[4])
print(nama[7])
print(nama[-1])
print(nama[-3])

"""**Slicing String**"""

Judul = 'Pelajaran Matematika Untuk SD'

print(Judul[0:5])
print(Judul[:10])
print(Judul[10:15])
print(Judul[-1:-3])
print(Judul[:-3])
print(Judul[:-5])

"""**Menghitung Panjang String**"""

print(len('Indonesia'))
print(len('Malaysia'))

"""**Memeriksa Karakter Awal String**"""

nomor_telepon_1 = '0871122334455'
nomor_telepon_2 = '6288776655300'
nomor_telepon_3 = '+6233003300330'

kode_negara = '+62'
print(nomor_telepon_1.startswith(kode_negara))
print(nomor_telepon_2.startswith(kode_negara))
print(nomor_telepon_3.startswith(kode_negara))

"""
**Memeriksa Karakter Akhir String**"""

email_1 = 'presiden@gmail.com'
email_2 = 'presiden@outlook.com'

print(email_1.endswith('gmail.com'))
print(email_2.endswith('gmail.com'))